import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { HeaderAuthActions } from "@/components/header-auth-actions";
import { AuthSessionProvider } from "@/components/session-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <ClerkProvider>
          <AuthSessionProvider>
            <header className="fixed right-4 top-4 z-50 flex items-center gap-2">
              <HeaderAuthActions />
              <ThemeToggle />
            </header>
            {children}
          </AuthSessionProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
